// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQwThQB332WguFmmulPIn4tnCC1tEAnlw',
    appId: '1:979930946453:web:e2b573413f20130d72f49c',
    messagingSenderId: '979930946453',
    projectId: 'sociowall-d541d',
    authDomain: 'sociowall-d541d.firebaseapp.com',
    storageBucket: 'sociowall-d541d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSu5pPhSQPnZhjyiC3ZgvnrjnSWfCuwE',
    appId: '1:979930946453:android:80e2635a3ddb304072f49c',
    messagingSenderId: '979930946453',
    projectId: 'sociowall-d541d',
    storageBucket: 'sociowall-d541d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuXJ_9pmdIKqlIu7qOvvwOZI5hRcEug-0',
    appId: '1:979930946453:ios:72ca3ea1b9b0611c72f49c',
    messagingSenderId: '979930946453',
    projectId: 'sociowall-d541d',
    storageBucket: 'sociowall-d541d.appspot.com',
    androidClientId:
        '979930946453-adt24rakiucbl0i2moren7fvjeign0sq.apps.googleusercontent.com',
    iosClientId:
        '979930946453-hfp6ckr8dvf9e6kl5hvcr9anibojg5nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuXJ_9pmdIKqlIu7qOvvwOZI5hRcEug-0',
    appId: '1:979930946453:ios:72ca3ea1b9b0611c72f49c',
    messagingSenderId: '979930946453',
    projectId: 'sociowall-d541d',
    storageBucket: 'sociowall-d541d.appspot.com',
    androidClientId:
        '979930946453-adt24rakiucbl0i2moren7fvjeign0sq.apps.googleusercontent.com',
    iosClientId:
        '979930946453-hfp6ckr8dvf9e6kl5hvcr9anibojg5nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizz',
  );
}
